### ISSUE TITLE
Dockerize the project

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/docurun#1]
Glad to see this project get created, especially as someone who uses SqlPage on a regular basis !

Want to ask if in your roadmap you would consider to dockerize this project, perhaps with option to mount 2 volumes volumes, one with the tests (docurun/index.md) as a ro volume and an output volume for md file + screenshots?

**Comment by lovasoa** [comment]
Thanks for the feedback ! I just published https://hub.docker.com/r/lovasoa/docurun
